## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [1]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])

print(vendas)

[[50 60 70 65 80]
 [85 90 78 92 88]
 [72 75 68 77 76]]


In [3]:
vendas_produto = np.sum(vendas, axis=1)
print('Total de vendas por produto é {}'.format(vendas_produto))

Total de vendas por produto é [325 433 368]


In [7]:
print('Total de vendas por produto A é {}'.format(vendas_produto[0]))
print('Total de vendas por produto B é {}'.format(vendas_produto[1]))
print('Total de vendas por produto C é {}'.format(vendas_produto[2]))

Total de vendas por produto A é 325
Total de vendas por produto B é 433
Total de vendas por produto C é 368


In [5]:
vendas_dia = np.sum(vendas, axis=0)
print(f'Total de vendas por dia é {vendas_dia}')

Total de vendas por dia é [207 225 216 234 244]


In [8]:
print(list(range(0,5)))

[0, 1, 2, 3, 4]


In [10]:
# loop for em um array, evitando redundância de código
for i in range(5):
    print(f'Vendas totais para o dia {i+1} é {vendas_dia[i]}')

Vendas totais para o dia 1 é 207
Vendas totais para o dia 2 é 225
Vendas totais para o dia 3 é 216
Vendas totais para o dia 4 é 234
Vendas totais para o dia 5 é 244
